version: "3.7"

services:

  adminer:
    image: adminer:latest
    environment:
      - VIRTUAL_HOST=adminer.yourdomain.local
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=adminer.yourdomain.local
      - LETSENCRYPT_EMAIL=email@yourdomain.local
    expose:
      - "8080"

networks:
  web:
    external: true