version: "3"

services:
  blog:
    image: wordpress:5.5
    environment:
      - WORDPRESS_DB_PASSWORD=your_secure_password
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blog.rule=Host(`blog.yourdomain.local`)"
      - "traefik.http.routers.blog.tls=true"
      - "traefik.http.routers.blog.tls.certresolver=lets-encrypt"
      - "traefik.port=80"
    networks:
      - internal
      - web

networks:
  web:
    external: true
  internal:
    external: false