version: "3.7"

services:
  postgres:
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_PASSWORD=your_secure_password
      - POSTGRES_USER=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    networks:
      - internal
    labels:
      - "traefik.enable=false"

networks:
  internal:
    external: false

volumes:
  postgres-data: