version: "3.7"

services:
  redis:
    image: redis:latest
    command: --appendonly yes --requirepass your_secure_password
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379
    networks:
      - internal
    deploy:
      restart_policy:
        condition: any
    labels:
      - "traefik.enable=false"

networks:
  internal:
    external: false

volumes:
  redis-data: