version: "3.7"

services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:

      # Frontend
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`portainer.yourdomain.local`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.services.frontend.loadbalancer.server.port=9000"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.routers.frontend.tls.certresolver=lets-encrypt"

      # Edge
      - "traefik.http.routers.edge.rule=Host(`edge.yourdomain.local`)"
      - "traefik.http.routers.edge.entrypoints=websecure"
      - "traefik.http.services.edge.loadbalancer.server.port=8000"
      - "traefik.http.routers.edge.service=edge"
      - "traefik.http.routers.edge.tls.certresolver=lets-encrypt"

    ports:
      - "9000:9000"
      - "8000:8000"
    networks:
      - internal
      - web

networks:
  web:
    external: true
  internal:
    external: false

volumes:
  portainer-data: