version: "3.3"

services:

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: --appendonly yes --requirepass your_secure_password
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379
    networks:
      - default

networks:
  default:
    external:
      name: nginx-proxy

volumes:
  redis-data: