version: "3.7"

services:
  mysql:
    image: 'mysql:5.7'
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=your_secure_password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - internal
    labels:
      - "traefik.enable=false"

networks:
  internal:
    external: false

volumes:
  mysql-data: