version: "3.7"

services:

  traefik:
    image: "traefik:v2.10"
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.docker.network=web
      - --api
      - --log.level=ERROR
      - --certificatesresolvers.lets-encrypt.acme.httpchallenge=true
      - --certificatesresolvers.lets-encrypt.acme.email=email@yourdomain.local #Set your email address here, is for the generation of SSL certificates with Let's Encrypt. 
      - --certificatesresolvers.lets-encrypt.acme.storage=./acme.json
      - --certificatesresolvers.lets-encrypt.acme.httpchallenge.entrypoint=web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/acme.json"
    labels:
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      # Dashboard
      - "traefik.http.routers.traefik.rule=Host(`traefik.yourdomain.local`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=admin"
      - "traefik.http.routers.traefik.tls.certresolver=lets-encrypt"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.middlewares.admin.basicauth.users=admin:$$2y$$05$$IbYykP9bwz8PAhYBxvDkAOdEwMkMvdUvE86OO8EcEAp16Otddn4a6"

networks:
  web:
    external: true