version: "3.3"

services:
  traefik:
    image: "traefik:latest"
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=web
      - --providers.file.directory=/etc/certs/dynamic
      - --api
      - --log.level=ERROR
      - --certificatesresolvers.lets-encrypt.acme.httpchallenge=true
      - --certificatesresolvers.lets-encrypt.acme.email=email@yourdomain.local #Set your email address here, is for the generation of SSL certificates with Let's Encrypt. 
      # - --certificatesresolvers.lets-encrypt.acme.storage=./acme.json
      - --certificatesresolvers.lets-encrypt.acme.httpchallenge.entrypoint=web

    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - traefik-data:/etc/certs #Volume where SSL certs are saved
      # - "./acme.json:/acme.json"
    labels:
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      # Dashboard
      - "traefik.http.routers.traefik.rule=Host(`traefik.yourdomain.local`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=admin"
      - "traefik.http.routers.traefik.tls.certresolver=lets-encrypt"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.middlewares.admin.basicauth.users=admin:$$2y$$05$$IbYykP9bwz8PAhYBxvDkAOdEwMkMvdUvE86OO8EcEAp16Otddn4a6"

networks:
  default:
    external:
      name: web

volumes:
  traefik-data: