version: "3.7"

services:
  traefik:
    image: "traefik:v2.10"
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik-web
      - --providers.file.directory=/etc/certs/dynamic
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.email=email@yourdomain.local #Set your email address here, is for the generation of SSL certificates with Let's Encrypt. 
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      - --api
      - --log.level=ERROR
      # - --certificatesresolvers.le.acme.storage=./acme.json

    ports:
      # Host mode is essential to work with IPv6
      # Listen on port 80, default for HTTP, necessary to redirect to HTTPS
      - target: 80
        published: 80
        mode: host
        protocol: tcp
      # Listen on port 443, default for HTTPS
      - target: 443
        published: 443
        mode: host
        protocol: tcp
      # additional ports
      - "9001:9001"
      - "9002:9002"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - traefik-data:/etc/certs #Volume where SSL certs are saved
      # - "./acme.json:/acme.json"

    labels:
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      # Dashboard
      - "traefik.http.routers.traefik.rule=Host(`traefik.yourdomain.local`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=admin"
      - "traefik.http.routers.traefik.tls.certresolver=lets-encrypt"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.middlewares.admin.basicauth.users=admin:$$2y$$05$$IbYykP9bwz8PAhYBxvDkAOdEwMkMvdUvE86OO8EcEAp16Otddn4a6"

networks:
  traefik-web:
    external: true

volumes:
  traefik-data: