version: "3.3"

services:

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=your_secure_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - default

networks:
  nginx-proxy:
    external: true

volumes:
  mysql-data: